fixtures:
  repositories:
    "archive": "https://github.com/voxpupuli/puppet-archive.git"
    "facts": "https://github.com/puppetlabs/puppetlabs-facts.git"
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    sonarqube: "#{source_dir}"
